### ISSUE TITLE
How to install ACE View for Protege v5.5?

### ISSUE THREAD

**Issue by carbonmetrics** [Kaljurand/aceview#18]
I am trying to install aceview in protege 5.5.0 Built beta-3, following http://attempto.ifi.uzh.ch/aceview/ 
 section 2. 
Both links do not result in protege picking up the plugins. 
I have downloaded the jar file, and this is also not picked up by protege.
How do I install aceview?

**Comment by Kaljurand** [comment]
ACE View is not compatible with newer versions of Protege. A Protege 4.2-compatible version is available at https://github.com/Kaljurand/aceview/releases

Unfortunately, I haven't found time to keep up to date with the developments in Protege and update ACE View accordingly. But you are welcome of contribute this update, ideally via a pull request.

**Comment by Kaljurand** [comment]
You could try to install the jar from https://github.com/Kaljurand/aceview/releases/tag/v2.0.0-alpha which seems compatible with Protege v5.5.

This is based on the work https://github.com/michael-aquilina/acepddl

**Comment by step21** [comment]
Are there any extra steps to install this? I placed it in the plugins directory, but no indication that it was loaded appears in the GUI and no errors either.

**Comment by Kaljurand** [comment]
@step21 You additionally need to enable the "Window -> Tabs -> ACE View" Protege menu option.

The installation instructions (on the Linux commandline) are:

```
cd plugins/
wget https://github.com/Kaljurand/aceview/releases/download/v2.0.0-alpha/ch.uzh.ifi.attempto.aceview.ui.view.jar
cd ..
./run.sh
```

On the console you should see something like:

```
Protege Desktop 
Version 5.5.0, Build  
 
----------------------------------- Platform ----------------------------------- 
Java: JVM 1.8.0_121-b13  Memory: 466M 
Language: en, Country: US 
Framework: Apache Software Foundation (1.8)  
OS: linux (5.4.0-64-generic) 
Processor: x86-64
 
 
------------------------------------ Plugins ----------------------------------- 
Plugin: OWLViz (5.0.3) 
Plugin: OWL Code Generation Plug-in (2.0.0) 
...
Plugin: HermiT Reasoner (1.4.3.456) 
Plugin: ACE View Tab (2.0.0.2018_12_15_1200) 
 
### Excluding compile: javax.swing.text.GlyphView::getBreakSpot
Creating and setting up empty (default) editor kit 
OWL API Version: 4.5.9.2019-02-01T07:24:44Z
...
```

**Comment by step21** [comment]
That option was not there, and on the console, there was no indication of the plugin being loaded. This was on MacOS, though I would have tried on Linux next.

The issue was, there are 2 plugin folders. I copied it into `Protege.app/Contents/Plugins/` but upon trying and googling again it turns out the correct folder is `Protege.app/Contents/Java/plugins/`.
After copying it to the right folder it worked. Thanks and sorry for taking up your time.
